'use client';

import { useCallback, useEffect, useState } from 'react';

type Search = { id: string; revision: number; name: string; enabled: boolean; criteria: Array<{ field: string; value: string; strength: string }> };
type Opportunity = { id: string; revision: number; title: string; listingUrl: string; location?: string | null; employer?: string | null; decision: string; applicationState?: string; dismissed?: boolean };
type Source = { id: string; revision: number; name: string; startUrl: string; allowedOrigins: string[]; enabled: boolean; supportStatus?: string; supportNote?: string | null };
type Resource = { id: string; relativePath: string; mediaType: string; sizeBytes: number; extractionState: string; segmentCount: number; errorCode?: string | null };
type Operation = { id: string; kind: string; state: string; progress: number; errorCode?: string | null; updatedAt: string };
type Run = { id: string; state: string; startedAt: string; finishedAt?: string | null; sourceCount: number; listingCount: number; errorCode?: string | null };
type Fact = { id: string; revision: number; key: string; value: unknown; status: string; provenance: unknown; sensitive: boolean; updatedAt: string };
type Application = { id: string; revision: number; listingId: string; state: string; blockers: unknown[]; updatedAt: string };
type ProfileQuestion = { id: string; state: string; question: string; answer?: string | null; evidence?: Array<{ quote: string; segmentId: string }>; errorCode?: string | null };
type Loadable<T> = { data: T; loading: boolean; error: string };

const initial = <T,>(data: T): Loadable<T> => ({ data, loading: true, error: '' });
function formatDate(value?: string | null) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function displayValue(value: unknown) { if (typeof value === 'string') return value; try { return JSON.stringify(value); } catch { return String(value); } }
function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'good' | 'warn' | 'bad' }) { const colors = { neutral: ['#eef2f6', '#344054'], good: ['#e8f7ee', '#176b3a'], warn: ['#fff4d6', '#855b00'], bad: ['#fdebea', '#b42318'] } as const; const [background, color] = colors[tone]; return <span style={{ background, color, borderRadius: 999, padding: '4px 9px', fontSize: 12, fontWeight: 700, whiteSpace: 'nowrap' }}>{children}</span>; }
function toneFor(state: string) { const lower = state.toLowerCase(); if (['completed', 'confirmed', 'submitted', 'enabled', 'ready', 'user_verified'].includes(lower)) return 'good' as const; if (['failed', 'error', 'blocked', 'conflicted', 'submission_unknown'].includes(lower)) return 'bad' as const; if (['queued', 'running', 'preparing', 'proposed', 'needs_review', 'paused'].includes(lower)) return 'warn' as const; return 'neutral' as const; }
function Status({ value }: { value: string }) { return <Badge tone={toneFor(value)}>{value.replaceAll('_', ' ')}</Badge>; }
function Empty({ children }: { children: React.ReactNode }) { return <p style={{ color: '#667085', marginBottom: 0 }}>{children}</p>; }
function Panel({ title, eyebrow, children, value, loading, error, onRetry }: { title: string; eyebrow?: string; children?: React.ReactNode; value?: number; loading: boolean; error: string; onRetry: () => void }) { return <section style={{ background: '#fff', border: '1px solid #e4e7ec', borderRadius: 16, padding: 22, boxShadow: '0 2px 8px rgba(16,24,40,.04)' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', gap: 12, marginBottom: 16 }}><div>{eyebrow && <div style={{ color: '#667085', fontSize: 12, fontWeight: 700, letterSpacing: '.08em', textTransform: 'uppercase' }}>{eyebrow}</div>}<h2 style={{ margin: '4px 0 0', fontSize: 20 }}>{title}</h2></div>{value !== undefined && <div style={{ fontSize: 28, fontWeight: 750, color: '#101828' }}>{value}</div>}</div>{loading ? <p style={{ color: '#667085' }} role="status">Loading {title.toLowerCase()}…</p> : error ? <div role="alert" style={{ color: '#b42318' }}><p style={{ marginTop: 0 }}>{error}</p><button onClick={onRetry}>Try again</button></div> : children}</section>; }

export default function Dashboard() {
  const [searches, setSearches] = useState<Loadable<Search[]>>(initial([])); const [opportunities, setOpportunities] = useState<Loadable<Opportunity[]>>(initial([])); const [sources, setSources] = useState<Loadable<Source[]>>(initial([])); const [resources, setResources] = useState<Loadable<Resource[]>>(initial([])); const [operations, setOperations] = useState<Loadable<Operation[]>>(initial([])); const [runs, setRuns] = useState<Loadable<Run[]>>(initial([])); const [facts, setFacts] = useState<Loadable<Fact[]>>(initial([])); const [applications, setApplications] = useState<Loadable<Application[]>>(initial([]));
  const [name, setName] = useState(''); const [sourceName, setSourceName] = useState(''); const [sourceUrl, setSourceUrl] = useState(''); const [question, setQuestion] = useState(''); const [questionResult, setQuestionResult] = useState<ProfileQuestion | null>(null); const [asking, setAsking] = useState(false); const [actionError, setActionError] = useState(''); const [uploading, setUploading] = useState(false); const [operationPollFailures, setOperationPollFailures] = useState(0); const [operationLastUpdated, setOperationLastUpdated] = useState<string | null>(null);
  const loadEndpoint = useCallback(async <T,>(url: string, setter: (value: Loadable<T>) => void, empty: T) => { setter({ data: empty, loading: true, error: '' }); try { const response = await fetch(url); if (!response.ok) throw new Error(); const payload = await response.json() as { data?: T | { items?: T } }; const data = payload.data && typeof payload.data === 'object' && 'items' in payload.data ? payload.data.items : payload.data; setter({ data: (data ?? payload) as T, loading: false, error: '' }); } catch { setter({ data: empty, loading: false, error: 'Unable to load this section.' }); } }, []);
  const refreshOperations = useCallback(async () => { if (document.visibilityState !== 'visible') return; try { const response = await fetch('/api/operations', { cache: 'no-store' }); if (!response.ok) throw new Error(); const payload = await response.json() as { data?: { items?: Operation[] } }; setOperations(current => ({ data: payload.data?.items ?? [], loading: false, error: '' })); setOperationPollFailures(0); setOperationLastUpdated(new Date().toISOString()); } catch { setOperationPollFailures(current => current + 1); } }, []);
  const refresh = useCallback(() => { void Promise.all([loadEndpoint('/api/searches', setSearches, []), loadEndpoint('/api/opportunities', setOpportunities, []), loadEndpoint('/api/sources', setSources, []), loadEndpoint('/api/resources', setResources, []), loadEndpoint('/api/operations', setOperations, []), loadEndpoint('/api/runs', setRuns, []), loadEndpoint('/api/profile/facts', setFacts, []), loadEndpoint('/api/applications', setApplications, [])]); }, [loadEndpoint]);
  useEffect(() => { refresh(); }, [refresh]);
  useEffect(() => { const poll = () => { void refreshOperations(); }; const interval = window.setInterval(poll, operationPollFailures >= 3 ? 10_000 : 2_000); document.addEventListener('visibilitychange', poll); return () => { window.clearInterval(interval); document.removeEventListener('visibilitychange', poll); }; }, [operationPollFailures, refreshOperations]);
  async function add() { if (!name.trim()) return; setActionError(''); const r = await fetch('/api/v1/searches', { method: 'POST', headers: { 'content-type': 'application/json', 'origin': location.origin, 'idempotency-key': `dashboard-search-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ name, enabled: false, criteria: [{ field: 'title', value: name, strength: 'required' }] }) }); if (r.ok) { setName(''); void loadEndpoint('/api/v1/searches', setSearches, []); } else setActionError('Unable to create search.'); }
  async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); location.href = '/auth/login'; }
  async function reviewFact(fact: Fact, action: 'confirm' | 'reject') { setActionError(''); const body = action === 'confirm' ? { value: fact.value, reason: 'Reviewed in dashboard.' } : { reason: 'Rejected in dashboard.' }; const response = await fetch(`/api/v1/facts/${fact.id}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': String(fact.revision), 'idempotency-key': `dashboard-fact-${fact.id}-${action}-${fact.revision}` }, body: JSON.stringify(body) }); if (response.ok) void loadEndpoint('/api/v1/profile/facts', setFacts, []); else setActionError('Unable to update profile fact; refresh and retry.'); }
  async function dismissOpportunity(opportunity: Opportunity) { setActionError(''); const response = await fetch(`/api/v1/opportunities/${opportunity.id}/dismiss`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': String(opportunity.revision), 'idempotency-key': `dashboard-opportunity-${opportunity.id}-dismiss-${opportunity.revision}` }, body: JSON.stringify({ dismissed: !opportunity.dismissed }) }); if (response.ok) void loadEndpoint('/api/v1/opportunities', setOpportunities, []); else setActionError('Unable to update opportunity; refresh and retry.'); }
  async function prepareApplication(opportunity: Opportunity) { setActionError(''); const response = await fetch('/api/v1/applications', { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'idempotency-key': `dashboard-application-create-${opportunity.id}` }, body: JSON.stringify({ listingId: opportunity.id }) }); if (response.ok) { void loadEndpoint('/api/v1/applications', setApplications, []); void loadEndpoint('/api/v1/opportunities', setOpportunities, []); } else setActionError('Unable to prepare application; refresh and retry.'); }
  async function addSource() { if (!sourceName.trim() || !sourceUrl.trim()) return; let origin: string; try { origin = new URL(sourceUrl).origin; } catch { setActionError('Enter a valid HTTP(S) source URL.'); return; } setActionError(''); const response = await fetch('/api/v1/sources', { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'idempotency-key': `dashboard-source-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ name: sourceName, startUrl: sourceUrl, allowedOrigins: [origin], enabled: false, supportStatus: 'unverified', supportNote: null }) }); if (response.ok) { setSourceName(''); setSourceUrl(''); void loadEndpoint('/api/v1/sources', setSources, []); } else setActionError('Unable to create source.'); }
  async function uploadPdf(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setActionError(''); setUploading(true); const form = new FormData(); form.set('file', file); try { const response = await fetch('/api/v1/resources', { method: 'POST', headers: { origin: location.origin, 'idempotency-key': `dashboard-resource-${file.name}-${file.size}-${file.lastModified}` }, body: form }); if (!response.ok) throw new Error(); void loadEndpoint('/api/resources', setResources, []); void loadEndpoint('/api/operations', setOperations, []); } catch { setActionError('Unable to upload PDF. Check that it is a valid PDF under 20 MiB.'); } finally { setUploading(false); } }
  async function askAboutMe() { if (!question.trim()) return; setActionError(''); setQuestionResult(null); setAsking(true); try { const response = await fetch('/api/v1/profile/questions', { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'idempotency-key': `dashboard-question-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ question }) }); if (!response.ok) throw new Error(); const created = await response.json() as { data: ProfileQuestion }; for (let attempt = 0; attempt < 60; attempt++) { await new Promise(resolve => window.setTimeout(resolve, 1000)); const status = await fetch(`/api/v1/profile/questions/${created.data.id}`, { cache: 'no-store' }); if (!status.ok) throw new Error(); const payload = await status.json() as { data: ProfileQuestion }; if (payload.data.state === 'succeeded' || payload.data.state === 'failed') { setQuestionResult(payload.data); return; } } throw new Error(); } catch { setActionError('Unable to answer that question. Check model readiness and try again.'); } finally { setAsking(false); } }
  async function toggleSource(source: Source) { setActionError(''); const response = await fetch(`/api/v1/sources/${source.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': `"${source.revision}"`, 'idempotency-key': `dashboard-source-${source.id}-${source.enabled ? 'disable' : 'enable'}-${source.revision}` }, body: JSON.stringify({ name: source.name, startUrl: source.startUrl, allowedOrigins: source.allowedOrigins, enabled: !source.enabled, supportStatus: source.supportStatus ?? 'unverified', supportNote: source.supportNote ?? null }) }); if (response.ok) void loadEndpoint('/api/v1/sources', setSources, []); else setActionError('Unable to update source; refresh and retry.'); }
  async function controlApplication(application: Application, action: 'cancel' | 'retry') { setActionError(''); const response = await fetch(`/api/v1/applications/${application.id}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': String(application.revision), 'idempotency-key': `dashboard-application-${application.id}-${action}-${application.revision}` }, body: JSON.stringify({}) }); if (response.ok) void loadEndpoint('/api/v1/applications', setApplications, []); else setActionError('Unable to update application; refresh and retry.'); }
  async function run(kind: string) { setActionError(''); const r = await fetch('/api/v1/operations', { method: 'POST', headers: { 'content-type': 'application/json', 'origin': location.origin, 'idempotency-key': `dashboard-${kind}-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ kind }) }); if (r.ok) void loadEndpoint('/api/v1/operations', setOperations, []); else setActionError('Unable to enqueue operation.'); }
  const tableStyle = { width: '100%', borderCollapse: 'collapse' as const, fontSize: 14 }; const cellStyle = { padding: '11px 8px', borderTop: '1px solid #eaecf0', textAlign: 'left' as const, verticalAlign: 'top' as const };
  const panel = (title: string, eyebrow: string, state: Loadable<unknown[]>, content: React.ReactNode) => <Panel title={title} eyebrow={eyebrow} value={state.data.length} loading={state.loading} error={state.error} onRetry={() => refresh()}>{content}</Panel>;
  return <main style={{ maxWidth: 1180, margin: '0 auto', padding: '28px 24px 64px', color: '#101828', background: '#f8fafc', minHeight: '100vh' }}><header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 20 }}><div><div style={{ color: '#6941c6', fontSize: 13, fontWeight: 700 }}>APPLICATION AUTOMATION</div><h1 style={{ margin: '5px 0' }}>Dashboard</h1><p style={{ margin: 0, color: '#667085' }}>Monitor discovery, applicant facts, and review-controlled applications.</p></div><div style={{ display: 'flex', gap: 8 }}><button onClick={refresh}>Refresh</button><button onClick={logout}>Sign out</button></div></header>{actionError && <p role="alert" style={{ color: '#b42318', background: '#fff1f0', padding: 12, borderRadius: 8 }}>{actionError}</p>}
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))', gap: 14, margin: '24px 0' }}>{[["Sources", sources.data.length, 'enabled'], ["Resources", resources.data.length, 'indexed'], ["Open opportunities", opportunities.data.length, 'review queue'], ["Applications", applications.data.length, 'attempts'], ["Active operations", operations.data.filter(o => ['queued', 'running'].includes(o.state)).length, operationPollFailures >= 3 ? `stale · last updated ${formatDate(operationLastUpdated)}` : 'updates every 2s while visible']].map(([label, count, note]) => <div key={String(label)} style={{ background: '#101828', color: '#fff', borderRadius: 14, padding: 18 }}><div style={{ color: '#d0d5dd', fontSize: 13 }}>{label}</div><div style={{ fontSize: 30, fontWeight: 750, marginTop: 6 }} aria-live="polite">{count}</div><div style={{ color: '#98a2b3', fontSize: 12 }}>{note}</div></div>)}</div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(360px,1fr))', gap: 18 }}>
      <Panel title="Searches" eyebrow="Discovery" value={searches.data.length} loading={searches.loading} error={searches.error} onRetry={refresh}><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><input aria-label="Search name" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. TypeScript internships" /><button onClick={add}>Create search</button></div><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', margin: '14px 0' }}><button onClick={() => run('scan')}>Queue discovery scan</button><button onClick={() => run('reindex')}>Reindex resources</button><button onClick={() => run('model_diagnostic')}>Test inference service</button></div>{searches.data.length === 0 ? <Empty>No searches yet. Create one to start discovery.</Empty> : <ul>{searches.data.map(s => <li key={s.id} style={{ margin: '8px 0' }}><strong>{s.name}</strong> <Status value={s.enabled ? 'enabled' : 'disabled'} /> <span style={{ color: '#667085' }}>· {s.criteria.length} criteria</span></li>)}</ul>}</Panel>
      {panel('Sources', 'Discovery inputs', sources, <><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 14 }}><input aria-label="Source name" value={sourceName} onChange={e => setSourceName(e.target.value)} placeholder="Source name" /><input aria-label="Source URL" value={sourceUrl} onChange={e => setSourceUrl(e.target.value)} placeholder="https://example.test/jobs" /><button onClick={addSource}>Add source</button></div>{sources.data.length === 0 ? <Empty>No sources configured yet.</Empty> : <ul style={{ paddingLeft: 18, marginBottom: 0 }}>{sources.data.map(s => <li key={s.id} style={{ margin: '10px 0' }}><strong>{s.name}</strong> <Status value={s.enabled ? 'enabled' : 'disabled'} /><button style={{ marginLeft: 8 }} onClick={() => toggleSource(s)}>{s.enabled ? 'Disable' : 'Enable'}</button><div style={{ color: '#667085', overflowWrap: 'anywhere' }}>{s.startUrl}</div>{s.supportStatus && <small>Support: {s.supportStatus.replaceAll('_', ' ')}</small>}</li>)}</ul>}</>)}
      {panel('Resources', 'Applicant materials', resources, <><div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', marginBottom: 14 }}><label htmlFor="pdf-upload"><strong>Upload a PDF</strong></label><input id="pdf-upload" type="file" accept=".pdf,application/pdf" onChange={uploadPdf} disabled={uploading} />{uploading && <span role="status">Uploading and queueing extraction…</span>}</div>{resources.data.length === 0 ? <Empty>No resources indexed yet. Upload a PDF or add files to the mounted resources folder.</Empty> : <table style={tableStyle}><thead><tr><th style={cellStyle}>File</th><th style={cellStyle}>State</th><th style={cellStyle}>Segments</th></tr></thead><tbody>{resources.data.slice(0, 8).map(r => <tr key={r.id}><td style={cellStyle}><strong>{r.relativePath}</strong><div style={{ color: '#667085', fontSize: 12 }}>{r.mediaType}</div></td><td style={cellStyle}><Status value={r.extractionState} />{r.errorCode && <div style={{ color: '#b42318', fontSize: 12 }}>{r.errorCode}</div>}</td><td style={cellStyle}>{r.segmentCount}</td></tr>)}</tbody></table>}</>)}
      <Panel title="Ask about me" eyebrow="Grounded profile assistant" loading={false} error="" onRetry={() => undefined}><p style={{ color: '#667085', marginTop: 0 }}>Questions are answered from confirmed facts and extracted PDF/text evidence.</p><textarea aria-label="Question about me" value={question} onChange={e => setQuestion(e.target.value)} placeholder="What experience do I have with TypeScript?" maxLength={2000} rows={3} style={{ width: '100%', boxSizing: 'border-box', marginBottom: 8 }} /><button onClick={askAboutMe} disabled={asking || !question.trim()}>{asking ? 'Thinking…' : 'Ask'}</button>{questionResult && <div style={{ marginTop: 14, borderTop: '1px solid #eaecf0', paddingTop: 12 }}><Status value={questionResult.state} />{questionResult.answer && <p style={{ whiteSpace: 'pre-wrap' }}>{questionResult.answer}</p>}{questionResult.evidence && questionResult.evidence.length > 0 && <small style={{ color: '#667085' }}>Grounded in {questionResult.evidence.length} resource segment(s).</small>}{questionResult.errorCode && <p role="alert" style={{ color: '#b42318' }}>{questionResult.errorCode}</p>}</div>}</Panel>
      {panel('Profile facts', 'Grounded applicant data', facts, facts.data.length === 0 ? <Empty>No profile facts yet. Confirmed facts will be available to preparation.</Empty> : <div>{facts.data.slice(0, 8).map(f => <div key={f.id} style={{ padding: '10px 0', borderTop: '1px solid #eaecf0' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><strong>{f.key}</strong><Status value={f.status} /></div><div style={{ marginTop: 4, overflowWrap: 'anywhere' }}>{displayValue(f.value)}</div><small style={{ color: '#667085' }}>{f.sensitive ? 'Sensitive · ' : ''}Updated {formatDate(f.updatedAt)}</small>{f.status !== 'confirmed' && <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><button onClick={() => reviewFact(f, 'confirm')}>Confirm</button><button onClick={() => reviewFact(f, 'reject')}>Reject</button></div>}</div>)}</div>)}
      {panel('Operations', 'Queue', operations, operations.data.length === 0 ? <Empty>No operations queued.</Empty> : <table style={tableStyle}><thead><tr><th style={cellStyle}>Operation</th><th style={cellStyle}>State</th><th style={cellStyle}>Progress</th></tr></thead><tbody>{operations.data.slice(0, 8).map(o => <tr key={o.id}><td style={cellStyle}>{o.kind.replaceAll('_', ' ')}</td><td style={cellStyle}><Status value={o.state} /></td><td style={cellStyle}>{o.progress}%<div style={{ color: '#667085', fontSize: 12 }}>{formatDate(o.updatedAt)}</div></td></tr>)}</tbody></table>)}
      {panel('Runs', 'Discovery history', runs, runs.data.length === 0 ? <Empty>No discovery runs yet. Queue a scan to see progress here.</Empty> : <table style={tableStyle}><thead><tr><th style={cellStyle}>Started</th><th style={cellStyle}>State</th><th style={cellStyle}>Listings</th></tr></thead><tbody>{runs.data.slice(0, 8).map(r => <tr key={r.id}><td style={cellStyle}>{formatDate(r.startedAt)}</td><td style={cellStyle}><Status value={r.state} />{r.errorCode && <div style={{ color: '#b42318', fontSize: 12 }}>{r.errorCode}</div>}</td><td style={cellStyle}>{r.listingCount}</td></tr>)}</tbody></table>)}
      {panel('Application states', 'Review-controlled workflow', applications, applications.data.length === 0 ? <Empty>No application attempts yet. Prepare an opportunity when you are ready.</Empty> : <div>{applications.data.slice(0, 8).map(a => <div key={a.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', padding: '11px 0', borderTop: '1px solid #eaecf0' }}><div><strong>Application {a.id.slice(0, 8)}</strong><div style={{ color: '#667085', fontSize: 12 }}>Listing {a.listingId.slice(0, 8)} · {formatDate(a.updatedAt)}</div>{a.blockers.length > 0 && <small style={{ color: '#b42318' }}>{a.blockers.length} blocker(s)</small>}</div><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Status value={a.state} />{['queued', 'preparing', 'ready', 'needs_review', 'needs_input'].includes(a.state) && <button onClick={() => controlApplication(a, 'cancel')}>Cancel</button>}{['failed', 'cancelled'].includes(a.state) && <button onClick={() => controlApplication(a, 'retry')}>Retry</button>}</div></div>)}</div>)}
      {panel('Discovered opportunities', 'Review queue', opportunities, opportunities.data.length === 0 ? <Empty>No listings discovered yet.</Empty> : <ul style={{ paddingLeft: 18, marginBottom: 0 }}>{opportunities.data.slice(0, 12).map(o => <li key={o.id} style={{ margin: '10px 0', opacity: o.dismissed ? .65 : 1 }}><a href={o.listingUrl} target="_blank" rel="noreferrer"><strong>{o.title}</strong></a>{o.employer && ` · ${o.employer}`}{o.location && ` · ${o.location}`}<div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 5 }}><Status value={o.dismissed ? 'dismissed' : o.applicationState ?? o.decision} /><button onClick={() => dismissOpportunity(o)}>{o.dismissed ? 'Restore' : 'Dismiss'}</button>{!o.dismissed && o.applicationState === 'not_started' && <button onClick={() => prepareApplication(o)}>Prepare application</button>}</div></li>)}</ul>)}
    </div>
  </main>;
}
