'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import './dashboard.css';

type Search = { id: string; revision: number; name: string; enabled: boolean; criteria: Array<{ field: string; value: string; strength: string }> };
type Opportunity = { id: string; revision: number; title: string; listingUrl: string; location?: string | null; employer?: string | null; decision: string; applicationState?: string; dismissed?: boolean };
type Source = { id: string; revision: number; name: string; startUrl: string; allowedOrigins: string[]; enabled: boolean; supportStatus?: string; supportNote?: string | null };
type Resource = { id: string; relativePath: string; mediaType: string; sizeBytes: number; extractionState: string; segmentCount: number; errorCode?: string | null };
type Operation = { id: string; kind: string; state: string; progress: number; errorCode?: string | null; updatedAt: string };
type Run = { id: string; state: string; startedAt: string; finishedAt?: string | null; sourceCount: number; listingCount: number; errorCode?: string | null };
type Fact = { id: string; revision: number; key: string; value: unknown; status: string; provenance: unknown; sensitive: boolean; updatedAt: string };
type Application = { id: string; revision: number; listingId: string; state: string; blockers: unknown[]; updatedAt: string };
type ProfileQuestion = { id: string; state: string; question: string; answer?: string | null; evidence?: Array<{ quote: string; segmentId: string }>; errorCode?: string | null };
type Loadable<T> = { data: T; loading: boolean; error: string };

const initial = <T,>(data: T): Loadable<T> => ({ data, loading: true, error: '' });
function formatDate(value?: string | null) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function displayValue(value: unknown) { if (typeof value === 'string') return value; try { return JSON.stringify(value); } catch { return String(value); } }
type IconName = 'grid' | 'search' | 'globe' | 'file' | 'spark' | 'activity' | 'arrow' | 'refresh' | 'check' | 'briefcase' | 'upload';
function Icon({ name, className = '' }: { name: IconName; className?: string }) {
  const paths: Record<IconName, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="2" /><rect x="14" y="3" width="7" height="7" rx="2" /><rect x="3" y="14" width="7" height="7" rx="2" /><rect x="14" y="14" width="7" height="7" rx="2" /></>,
    search: <><circle cx="10.5" cy="10.5" r="6.5" /><path d="m16 16 5 5" /></>,
    globe: <><circle cx="12" cy="12" r="9" /><ellipse cx="12" cy="12" rx="4" ry="9" /><path d="M3 12h18" /></>,
    file: <><path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9Z" /><path d="M14 3v6h6M8 13h8M8 17h5" /></>,
    spark: <><path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z" /><path d="m20 2 .5 1.5L22 4l-1.5.5L20 6l-.5-1.5L18 4l1.5-.5Z" /></>,
    activity: <><path d="M3 12h4l3-8 4 16 3-8h4" /></>,
    arrow: <><path d="M5 12h14m-5-5 5 5-5 5" /></>,
    refresh: <><path d="M20 7v5h-5M4 17v-5h5" /><path d="M6.1 7a7 7 0 0 1 11.6-1L20 9M4 15l2.3 3A7 7 0 0 0 18 17" /></>,
    check: <path d="m5 12 4 4L19 6" />,
    briefcase: <><rect x="3" y="7" width="18" height="14" rx="3" /><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12a21 21 0 0 0 18 0M12 11v4" /></>,
    upload: <><path d="M12 16V3m-5 5 5-5 5 5M4 15v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4" /></>,
  };
  return <svg className={className} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'good' | 'warn' | 'bad' }) { return <span className={`badge badge-${tone}`}><span aria-hidden="true" />{children}</span>; }
function toneFor(state: string) { const lower = state.toLowerCase(); if (['completed', 'confirmed', 'submitted', 'enabled', 'ready', 'user_verified', 'succeeded', 'extracted'].includes(lower)) return 'good' as const; if (['failed', 'error', 'blocked', 'conflicted', 'submission_unknown'].includes(lower)) return 'bad' as const; if (['queued', 'running', 'preparing', 'proposed', 'needs_review', 'paused', 'partial'].includes(lower)) return 'warn' as const; return 'neutral' as const; }
function Status({ value }: { value: string }) { return <Badge tone={toneFor(value)}>{value.replaceAll('_', ' ')}</Badge>; }
function Empty({ children, icon = 'spark' }: { children: React.ReactNode; icon?: IconName }) { return <div className="empty-state"><span className="empty-icon"><Icon name={icon} /></span><p>{children}</p></div>; }
function panelId(title: string) { return title.toLowerCase().replaceAll(' ', '-'); }
function Panel({ title, eyebrow, children, value, loading, error, onRetry }: { title: string; eyebrow?: string; children?: React.ReactNode; value?: number; loading: boolean; error: string; onRetry: () => void }) {
  return <section id={panelId(title)} className={`panel${title === 'Discovered opportunities' ? ' panel-wide' : ''}`} aria-labelledby={`${panelId(title)}-title`}>
    <div className="panel-header"><div>{eyebrow && <div className="panel-eyebrow">{eyebrow}</div>}<h2 className="panel-title" id={`${panelId(title)}-title`}>{title}</h2></div>{value !== undefined && <span className="panel-count">{loading ? '?' : value}</span>}</div>
    <div className="panel-body">{loading ? <div className="empty-state loading-state" role="status"><span className="loading-dot" />Loading {title.toLowerCase()}?</div> : error ? <div className="section-error" role="alert"><p>{error}</p><button className="secondary" onClick={onRetry}>Try again</button></div> : children}</div>
  </section>;
}

export default function Dashboard() {
  const [activeSection, setActiveSection] = useState('overview');
  const [searches, setSearches] = useState<Loadable<Search[]>>(initial([])); const [opportunities, setOpportunities] = useState<Loadable<Opportunity[]>>(initial([])); const [sources, setSources] = useState<Loadable<Source[]>>(initial([])); const [resources, setResources] = useState<Loadable<Resource[]>>(initial([])); const [operations, setOperations] = useState<Loadable<Operation[]>>(initial([])); const [runs, setRuns] = useState<Loadable<Run[]>>(initial([])); const [facts, setFacts] = useState<Loadable<Fact[]>>(initial([])); const [applications, setApplications] = useState<Loadable<Application[]>>(initial([]));
  const [name, setName] = useState(''); const [sourceName, setSourceName] = useState(''); const [sourceUrl, setSourceUrl] = useState(''); const [question, setQuestion] = useState(''); const [questionResult, setQuestionResult] = useState<ProfileQuestion | null>(null); const [asking, setAsking] = useState(false); const [actionError, setActionError] = useState(''); const [uploading, setUploading] = useState(false); const [operationPollFailures, setOperationPollFailures] = useState(0); const [operationLastUpdated, setOperationLastUpdated] = useState<string | null>(null);
  const endpointGenerations = useRef(new Map<string, number>());
  const observedOperations = useRef(new Map<string, string>());
  const loadEndpoint = useCallback(async <T,>(url: string, setter: (value: Loadable<T>) => void, empty: T, background = false) => { const key = url.replace(/^\/api\/v1(?=\/|$)/, '/api'); const generation = (endpointGenerations.current.get(key) ?? 0) + 1; endpointGenerations.current.set(key, generation); if (!background) setter({ data: empty, loading: true, error: '' }); try { const response = await fetch(url); if (!response.ok) throw new Error(); const payload = await response.json() as { data?: T | { items?: T } }; const data = payload.data && typeof payload.data === 'object' && 'items' in payload.data ? payload.data.items : payload.data; if (endpointGenerations.current.get(key) !== generation) return; setter({ data: (data ?? payload) as T, loading: false, error: '' }); } catch { if (!background && endpointGenerations.current.get(key) === generation) setter({ data: empty, loading: false, error: 'Unable to load this section.' }); } }, []);
  const refresh = useCallback((background = false) => { void Promise.all([loadEndpoint('/api/searches', setSearches, [], background), loadEndpoint('/api/opportunities', setOpportunities, [], background), loadEndpoint('/api/sources', setSources, [], background), loadEndpoint('/api/resources', setResources, [], background), loadEndpoint('/api/operations', setOperations, [], background), loadEndpoint('/api/runs', setRuns, [], background), loadEndpoint('/api/profile/facts', setFacts, [], background), loadEndpoint('/api/applications', setApplications, [], background)]); }, [loadEndpoint]);
  const refreshOperations = useCallback(async () => { if (document.visibilityState !== 'visible') return; const generation = (endpointGenerations.current.get('/api/operations') ?? 0) + 1; endpointGenerations.current.set('/api/operations', generation); try { const response = await fetch('/api/operations', { cache: 'no-store' }); if (!response.ok) throw new Error(); const payload = await response.json() as { data?: { items?: Operation[] } }; if (endpointGenerations.current.get('/api/operations') !== generation) return; const items = payload.data?.items ?? []; const terminal = new Set(['succeeded', 'failed', 'cancelled', 'completed']); const newlyTerminal = items.some(operation => terminal.has(operation.state) && observedOperations.current.get(operation.id) !== operation.state); items.forEach(operation => observedOperations.current.set(operation.id, operation.state)); setOperations(current => ({ data: items, loading: false, error: '' })); if (newlyTerminal) refresh(true); setOperationPollFailures(0); setOperationLastUpdated(new Date().toISOString()); } catch { setOperationPollFailures(current => current + 1); } }, [refresh]);
  useEffect(() => { refresh(); }, [refresh]);
  useEffect(() => { const poll = () => { void refreshOperations(); }; const interval = window.setInterval(poll, operationPollFailures >= 3 ? 10_000 : 2_000); document.addEventListener('visibilitychange', poll); return () => { window.clearInterval(interval); document.removeEventListener('visibilitychange', poll); }; }, [operationPollFailures, refreshOperations]);
  async function add() {try { if (!name.trim()) return; setActionError(''); const r = await fetch('/api/v1/searches', { method: 'POST', headers: { 'content-type': 'application/json', 'origin': location.origin, 'idempotency-key': `dashboard-search-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ name, enabled: false, criteria: [{ field: 'title', value: name, strength: 'required' }] }) }); if (r.ok) { setName(''); void loadEndpoint('/api/v1/searches', setSearches, []); } else setActionError('Unable to create search.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function reviewFact(fact: Fact, action: 'confirm' | 'reject') {try { setActionError(''); const body = action === 'confirm' ? { value: fact.value, reason: 'Reviewed in dashboard.' } : { reason: 'Rejected in dashboard.' }; const response = await fetch(`/api/v1/facts/${fact.id}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': String(fact.revision), 'idempotency-key': `dashboard-fact-${fact.id}-${action}-${fact.revision}` }, body: JSON.stringify(body) }); if (response.ok) void loadEndpoint('/api/v1/profile/facts', setFacts, []); else setActionError('Unable to update profile fact; refresh and retry.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function dismissOpportunity(opportunity: Opportunity) {try { setActionError(''); const response = await fetch(`/api/v1/opportunities/${opportunity.id}/dismiss`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': String(opportunity.revision), 'idempotency-key': `dashboard-opportunity-${opportunity.id}-dismiss-${opportunity.revision}` }, body: JSON.stringify({ dismissed: !opportunity.dismissed }) }); if (response.ok) void loadEndpoint('/api/v1/opportunities', setOpportunities, []); else setActionError('Unable to update opportunity; refresh and retry.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function prepareApplication(opportunity: Opportunity) {try { setActionError(''); const response = await fetch('/api/v1/applications', { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'idempotency-key': `dashboard-application-create-${opportunity.id}` }, body: JSON.stringify({ listingId: opportunity.id }) }); if (response.ok) { void loadEndpoint('/api/v1/applications', setApplications, []); void loadEndpoint('/api/v1/opportunities', setOpportunities, []); } else setActionError('Unable to prepare application; refresh and retry.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function addSource() {try { if (!sourceName.trim() || !sourceUrl.trim()) return; let origin: string; try { origin = new URL(sourceUrl).origin; } catch { setActionError('Enter a valid HTTP(S) source URL.'); return; } setActionError(''); const response = await fetch('/api/v1/sources', { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'idempotency-key': `dashboard-source-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ name: sourceName, startUrl: sourceUrl, allowedOrigins: [origin], enabled: false, supportStatus: 'unverified', supportNote: null }) }); if (response.ok) { setSourceName(''); setSourceUrl(''); void loadEndpoint('/api/v1/sources', setSources, []); } else setActionError('Unable to create source.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function uploadPdf(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setActionError(''); setUploading(true); const form = new FormData(); form.set('file', file); try { const response = await fetch('/api/v1/resources', { method: 'POST', headers: { origin: location.origin, 'idempotency-key': `dashboard-resource-${file.name}-${file.size}-${file.lastModified}` }, body: form }); if (!response.ok) throw new Error(); void loadEndpoint('/api/resources', setResources, []); void loadEndpoint('/api/operations', setOperations, []); } catch { setActionError('Unable to upload PDF. Check that it is a valid PDF under 20 MiB.'); } finally { setUploading(false); } }
  async function askAboutMe() { if (!question.trim()) return; setActionError(''); setQuestionResult(null); setAsking(true); try { const response = await fetch('/api/v1/profile/questions', { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'idempotency-key': `dashboard-question-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ question }) }); if (!response.ok) throw new Error(); const created = await response.json() as { data: ProfileQuestion }; for (let attempt = 0; attempt < 60; attempt++) { await new Promise(resolve => window.setTimeout(resolve, 1000)); const status = await fetch(`/api/v1/profile/questions/${created.data.id}`, { cache: 'no-store' }); if (!status.ok) throw new Error(); const payload = await status.json() as { data: ProfileQuestion }; if (payload.data.state === 'succeeded' || payload.data.state === 'failed') { setQuestionResult(payload.data); return; } } throw new Error(); } catch { setActionError('Unable to answer that question. Check model readiness and try again.'); } finally { setAsking(false); } }
  async function saveOrigins(source: Source, value: string) {try {
    setActionError('');
    let allowedOrigins: string[];
    try { allowedOrigins = [...new Set([new URL(source.startUrl).origin, ...value.split(/[\s,]+/).filter(Boolean).map(origin => { const url = new URL(origin); if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) throw new Error(); return url.origin; })])]; }
    catch { setActionError('Enter valid HTTP(S) origins, separated by commas.'); return; }
    const response = await fetch(`/api/v1/sources/${source.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'if-match': `"${source.revision}"`, 'idempotency-key': `dashboard-origins-${source.id}-${Date.now()}` }, body: JSON.stringify({ name: source.name, startUrl: source.startUrl, allowedOrigins, enabled: source.enabled, supportStatus: source.supportStatus ?? 'unverified', supportNote: source.supportNote ?? null }) });
    if (response.ok) void loadEndpoint('/api/v1/sources', setSources, []); else setActionError('Unable to update allowed origins; release the browser session, refresh and retry.');
  } catch { setActionError('Unable to connect. Please try again.'); }}
  async function toggleSource(source: Source) {try { setActionError(''); const response = await fetch(`/api/v1/sources/${source.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': `"${source.revision}"`, 'idempotency-key': `dashboard-source-${source.id}-${source.enabled ? 'disable' : 'enable'}-${source.revision}` }, body: JSON.stringify({ name: source.name, startUrl: source.startUrl, allowedOrigins: source.allowedOrigins, enabled: !source.enabled, supportStatus: source.supportStatus ?? 'unverified', supportNote: source.supportNote ?? null }) }); if (response.ok) void loadEndpoint('/api/v1/sources', setSources, []); else setActionError('Unable to update source; refresh and retry.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function controlApplication(application: Application, action: 'cancel' | 'retry') {try { setActionError(''); const response = await fetch(`/api/v1/applications/${application.id}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin, 'if-match': String(application.revision), 'idempotency-key': `dashboard-application-${application.id}-${action}-${application.revision}` }, body: JSON.stringify({}) }); if (response.ok) void loadEndpoint('/api/v1/applications', setApplications, []); else setActionError('Unable to update application; refresh and retry.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  async function run(kind: string) {try { setActionError(''); const r = await fetch('/api/v1/operations', { method: 'POST', headers: { 'content-type': 'application/json', 'origin': location.origin, 'idempotency-key': `dashboard-${kind}-${Date.now()}-${Math.random().toString(16).slice(2)}` }, body: JSON.stringify({ kind }) }); if (r.ok) void loadEndpoint('/api/v1/operations', setOperations, []); else setActionError('Unable to enqueue operation.'); } catch { setActionError('Unable to connect. Please try again.'); }}
  const panel = (title: string, eyebrow: string, state: Loadable<unknown[]>, content: React.ReactNode) => <Panel title={title} eyebrow={eyebrow} value={state.data.length} loading={state.loading} error={state.error} onRetry={() => refresh()}>{content}</Panel>;
  const activeOperations = operations.data.filter(o => ['queued', 'running'].includes(o.state)).length;
  const stats: Array<{ label: string; value: number; note: string; icon: IconName; loading: boolean }> = [
    { label: 'Active sources', value: sources.data.filter(s => s.enabled).length, note: `${sources.data.length} connected in total`, icon: 'globe', loading: sources.loading },
    { label: 'Resources', value: resources.data.filter(r => r.extractionState === 'extracted').length, note: 'Ready to inform your profile', icon: 'file', loading: resources.loading },
    { label: 'Opportunities', value: opportunities.data.filter(o => !o.dismissed).length, note: 'In your review queue', icon: 'search', loading: opportunities.loading },
    { label: 'Applications', value: applications.data.length, note: 'Your progress, at a glance', icon: 'briefcase', loading: applications.loading },
    { label: 'Active operations', value: activeOperations, note: operationPollFailures >= 3 ? `Updates delayed — ${formatDate(operationLastUpdated)}` : 'Queued or in progress', icon: 'activity', loading: operations.loading },
  ];
  const navigation: Array<{ id: string; label: string; icon: IconName }> = [
    { id: 'overview', label: 'Overview', icon: 'grid' }, { id: 'searches', label: 'Discovery', icon: 'search' },
    { id: 'sources', label: 'Sources', icon: 'globe' }, { id: 'resources', label: 'My resources', icon: 'file' },
    { id: 'discovered-opportunities', label: 'Opportunities', icon: 'briefcase' }, { id: 'operations', label: 'Activity', icon: 'activity' },
  ];
  return <div className="dashboard">
    <a className="skip-link" href="#overview">Skip to dashboard</a>
    <aside className="sidebar" aria-label="Workspace navigation">
      <a className="brand" href="#overview" onClick={() => setActiveSection('overview')}><span className="brand-mark"><Icon name="spark" /></span><span className="brand-name">Apply<span>YOUR NEXT CHAPTER</span></span></a>
      <div className="sidebar-label">WORKSPACE</div>
      <nav className="sidebar-nav">{navigation.map(item => <a key={item.id} href={`#${item.id}`} className={activeSection === item.id ? 'nav-active' : ''} aria-current={activeSection === item.id ? 'location' : undefined} aria-label={item.label} title={item.label} onClick={() => setActiveSection(item.id)}><Icon name={item.icon} className="nav-icon" /><span>{item.label}</span></a>)}</nav>
      <div className="sidebar-footer"><div className="workspace-avatar">Y</div><div><strong>Your workspace</strong><span>Personal & local</span></div><span className="workspace-dot" /></div>
    </aside>
    <main className="dashboard-main">
      <header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>Overview</strong></div><div className="topbar-actions"><span className="local-pill"><span />Local workspace</span><span className="topbar-avatar" aria-label="Your personal workspace">Y</span></div></header>
      <div className="dashboard-content" id="overview">
        <div className="page-heading"><div><div className="eyebrow">A LITTLE FOCUS. A LOT OF POSSIBILITY.</div><h1>Your next move starts here.</h1><p>Discover opportunities, build your profile, and keep everything moving.</p></div><div className="heading-actions"><button className="secondary" onClick={() => refresh()}><Icon name="refresh" />Refresh</button></div></div>
        {actionError && <div className="action-error" role="alert">{actionError}</div>}
        <section className="hero-banner" aria-label="Start discovery"><div className="hero-copy"><span className="hero-label"><Icon name="spark" />A more thoughtful job search</span><h2>Less busywork.<br />More possibility.</h2><p>Bring your sources and experience together.<br className="desktop-break" /> Let discovery do the searching. You make the next move.</p><div className="hero-actions"><button className="primary" onClick={() => run('scan')}>Start discovery<Icon name="arrow" /></button><a href="#sources" onClick={() => setActiveSection('sources')}>Manage sources <span aria-hidden="true">?</span></a></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-card art-card-back"><span className="art-line" /><span className="art-line short" /></div><div className="art-card art-card-front"><span className="art-card-icon"><Icon name="briefcase" /></span><span className="art-line" /><span className="art-line short" /><span className="art-tag">Your next opportunity</span></div><span className="art-check"><Icon name="check" /></span><span className="art-spark"><Icon name="spark" /></span></div></section>
        <div className="stats-grid" aria-label="Workspace summary">{stats.map(stat => <div className="stat-card" key={stat.label}><div className="stat-top"><span className="stat-label">{stat.label}</span><span className="stat-icon"><Icon name={stat.icon} /></span></div><div className="stat-value" aria-live="polite">{stat.loading ? '?' : stat.value}</div><div className="stat-note">{stat.note}</div></div>)}</div>
        <div className="section-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h2>Your workspace, connected.</h2></div><span className="helper-text">Everything you need for the next step</span></div>
        <div className="dashboard-grid">
          <Panel title="Searches" eyebrow="01 / Discover" value={searches.data.length} loading={searches.loading} error={searches.error} onRetry={() => refresh()}>
            <p className="muted">Give your next opportunity a direction.</p><form className="form-row" onSubmit={event => { event.preventDefault(); void add(); }}><input aria-label="Search name" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. TypeScript internships" /><button className="primary" disabled={!name.trim()}>Create search</button></form>
            <div className="record-actions utility-actions"><button className="ghost" onClick={() => run('scan')}><Icon name="search" />Queue discovery scan</button><button className="ghost" onClick={() => run('reindex')}>Reindex resources</button><button className="ghost" onClick={() => run('model_diagnostic')}>Test inference service</button></div>
            {searches.data.length === 0 ? <Empty icon="search">A fresh start. Create your first search to focus your discovery.</Empty> : <ul className="record-list">{searches.data.map(s => <li className="record" key={s.id}><div className="record-heading"><strong>{s.name}</strong><Status value={s.enabled ? 'enabled' : 'disabled'} /></div><div className="record-meta">{s.criteria.length} search criteria</div></li>)}</ul>}
          </Panel>
          {panel('Sources', '02 / Connect', sources, <>
            <p className="muted">The places you want your next opportunity to come from.</p><form className="form-row source-form" onSubmit={event => { event.preventDefault(); void addSource(); }}><input aria-label="Source name" value={sourceName} onChange={e => setSourceName(e.target.value)} placeholder="Source name" /><input aria-label="Source URL" type="url" value={sourceUrl} onChange={e => setSourceUrl(e.target.value)} placeholder="https://example.com/jobs" /><button className="primary" disabled={!sourceName.trim() || !sourceUrl.trim()}>Add source</button></form>
            {sources.data.length === 0 ? <Empty icon="globe">Your search starts somewhere. Connect a job board to get going.</Empty> : <ul className="record-list">{sources.data.map(s => <li className="record" key={s.id}><div className="record-heading"><strong>{s.name}</strong><Status value={s.enabled ? 'enabled' : 'disabled'} /></div><div className="record-meta source-url">{s.startUrl}</div><div className="record-actions"><a className="button secondary" href={`/browser/${s.id}`}><Icon name="globe" />Sign in / manage browser</a><button className="ghost" onClick={() => toggleSource(s)}>{s.enabled ? 'Disable' : 'Enable'}</button></div><details className="source-origins"><summary>Connection settings</summary><form key={`${s.id}-${s.revision}`} onSubmit={event => { event.preventDefault(); void saveOrigins(s, String(new FormData(event.currentTarget).get('origins') ?? '')); }}><label className="field">Allowed website and login origins<input name="origins" defaultValue={s.allowedOrigins.join(', ')} /></label><button className="secondary" type="submit">Save origins</button></form>{s.supportStatus && <p className="helper-text">Support: {s.supportStatus.replaceAll('_', ' ')}</p>}</details></li>)}</ul>}
          </>)}
          {panel('Resources', '03 / Tell your story', resources, <>
            <label className="upload-zone" htmlFor="pdf-upload"><span className="upload-icon"><Icon name="upload" /></span><strong>{uploading ? 'Adding your document…' : 'Add a little more about you'}</strong><span>Choose a PDF résumé, portfolio, or supporting document</span><span className="upload-limit">PDF up to 20 MB</span><input className="visually-hidden" id="pdf-upload" type="file" accept=".pdf,application/pdf" onChange={uploadPdf} disabled={uploading} /></label>{uploading && <p role="status" className="helper-text">Uploading and queueing extraction…</p>}
            {resources.data.length === 0 ? <Empty icon="file">Your experience belongs here. Add a document to build your profile.</Empty> : <div className="table-wrap"><table><thead><tr><th>Document</th><th>Status</th><th>Segments</th></tr></thead><tbody>{resources.data.slice(0, 8).map(r => <tr key={r.id}><td><strong>{r.relativePath}</strong><div className="record-meta">{r.mediaType}</div></td><td><Status value={r.extractionState} />{r.errorCode && <div className="error-text">{r.errorCode}</div>}</td><td>{r.segmentCount}</td></tr>)}</tbody></table></div>}
          </>)}
          <Panel title="Ask about me" eyebrow="Your profile assistant" loading={false} error="" onRetry={() => undefined}>
            <div className="assistant-intro"><span className="assistant-icon"><Icon name="spark" /></span><p className="muted">A fresh perspective on your experience, grounded in your documents and confirmed facts.</p></div><label className="visually-hidden" htmlFor="profile-question">Question about me</label><textarea id="profile-question" aria-label="Question about me" value={question} onChange={e => setQuestion(e.target.value)} placeholder="What experience do I have with TypeScript?" maxLength={2000} rows={4} /><div className="assistant-actions"><span className="helper-text">Your experience. In your words.</span><button className="primary" onClick={askAboutMe} disabled={asking || !question.trim()}><Icon name="spark" />{asking ? 'Thinking?' : 'Ask assistant'}</button></div>
            {questionResult && <div className="profile-answer"><Status value={questionResult.state} />{questionResult.answer && <p>{questionResult.answer}</p>}{questionResult.evidence && questionResult.evidence.length > 0 && <small className="helper-text">Grounded in {questionResult.evidence.length} resource segment(s).</small>}{questionResult.errorCode && <p role="alert" className="error-text">{questionResult.errorCode}</p>}</div>}
          </Panel>
          {panel('Profile facts', 'The details that make you, you', facts, facts.data.length === 0 ? <Empty icon="check">A clearer picture, one fact at a time. Your confirmed experience will appear here.</Empty> : <ul className="record-list">{facts.data.slice(0, 8).map(f => <li className="record" key={f.id}><div className="record-heading"><strong>{f.key}</strong><Status value={f.status} /></div><p className="fact-value">{displayValue(f.value)}</p><div className="record-meta">{f.sensitive ? 'Sensitive · ' : ''}Updated {formatDate(f.updatedAt)}</div>{f.status !== 'confirmed' && <div className="record-actions"><button className="secondary" onClick={() => reviewFact(f, 'confirm')}>Confirm</button><button className="ghost danger" onClick={() => reviewFact(f, 'reject')}>Reject</button></div>}</li>)}</ul>)}
          {panel('Operations', 'Behind the scenes', operations, operations.data.length === 0 ? <Empty icon="activity">All quiet for now. Your queued and active tasks will show up here.</Empty> : <div className="table-wrap"><table><thead><tr><th>Operation</th><th>Status</th><th>Progress</th></tr></thead><tbody>{operations.data.slice(0, 8).map(o => <tr key={o.id}><td><strong>{o.kind.replaceAll('_', ' ')}</strong><div className="record-meta">{formatDate(o.updatedAt)}</div></td><td><Status value={o.state} /></td><td><div className="progress-label">{o.progress}%</div><div className="progress-track" role="progressbar" aria-label={o.kind.replaceAll('_', ' ')} aria-valuenow={o.progress} aria-valuemin={0} aria-valuemax={100}><div className="progress-fill" style={{ width: `${Math.max(0, Math.min(100, o.progress))}%` }} /></div></td></tr>)}</tbody></table></div>)}
          {panel('Runs', 'Discovery history', runs, runs.data.length === 0 ? <Empty icon="search">The beginning of something good. Start discovery to see your first results.</Empty> : <div className="table-wrap"><table><thead><tr><th>Started</th><th>Status</th><th>Listings</th></tr></thead><tbody>{runs.data.slice(0, 8).map(r => <tr key={r.id}><td>{formatDate(r.startedAt)}</td><td><Status value={r.state} />{r.errorCode && <div className="error-text">{r.errorCode}</div>}</td><td>{r.listingCount}</td></tr>)}</tbody></table></div>)}
          {panel('Application states', 'Every step, in your hands', applications, applications.data.length === 0 ? <Empty icon="briefcase">Your next chapter is unwritten. Prepare an opportunity when you find the right fit.</Empty> : <ul className="record-list">{applications.data.slice(0, 8).map(a => <li className="record" key={a.id}><div className="record-heading"><strong>Application {a.id.slice(0, 8)}</strong><Status value={a.state} /></div><div className="record-meta">Listing {a.listingId.slice(0, 8)} · {formatDate(a.updatedAt)}</div>{a.blockers.length > 0 && <small className="error-text">{a.blockers.length} blocker(s)</small>}<div className="record-actions">{['queued', 'preparing', 'ready', 'needs_review', 'needs_input'].includes(a.state) && <button className="ghost danger" onClick={() => controlApplication(a, 'cancel')}>Cancel</button>}{['failed', 'cancelled'].includes(a.state) && <button className="secondary" onClick={() => controlApplication(a, 'retry')}>Retry</button>}</div></li>)}</ul>)}
          {panel('Discovered opportunities', 'Possibilities worth a closer look', opportunities, opportunities.data.length === 0 ? <Empty icon="briefcase">Room for your next opportunity. Connect a source and start discovery to fill it.</Empty> : <ul className="record-list opportunity-list">{opportunities.data.slice(0, 12).map(o => <li className={`record opportunity${o.dismissed ? ' dismissed' : ''}`} key={o.id}><div className="opportunity-icon"><Icon name="briefcase" /></div><div className="opportunity-content"><a className="opportunity-title" href={o.listingUrl} target="_blank" rel="noreferrer">{o.title}<span aria-hidden="true">→</span></a><div className="record-meta">{[o.employer, o.location].filter(Boolean).join(' · ') || 'View listing for details'}</div><div className="record-actions"><Status value={o.dismissed ? 'dismissed' : o.applicationState ?? o.decision} /><button className="ghost" onClick={() => dismissOpportunity(o)}>{o.dismissed ? 'Restore' : 'Dismiss'}</button>{!o.dismissed && o.applicationState === 'not_started' && <button className="secondary" onClick={() => prepareApplication(o)}>Prepare application<Icon name="arrow" /></button>}</div></div></li>)}</ul>)}
        </div>
        <footer className="dashboard-footer"><span><Icon name="spark" />A little less busywork. A little more you.</span><span>Your workspace · Your pace</span></footer>
      </div>
    </main>
  </div>;
}
