import Database from 'better-sqlite3';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { assertSchema, openDatabase, schemaVersion } from './database.ts';

export type BackupFile = { root: 'artifacts' | 'profiles'; key: string; sha256: string; sizeBytes: number };
export type BackupManifest = { manifestVersion: 1; schemaVersion: number; createdAt: string; files: BackupFile[] };
export type BackupHooks = { stopWork: () => void | Promise<void>; checkpoint: () => void | Promise<void>; waitForSubmissions: () => void | Promise<void> };
const hash = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');
function tree(root: string, kind: BackupFile['root']): BackupFile[] { if (!existsSync(root)) return []; const result: BackupFile[] = []; const visit = (dir: string) => { for (const entry of readdirSync(dir, { withFileTypes: true })) { const path = join(dir, entry.name); if (entry.isDirectory()) visit(path); else if (entry.isFile()) result.push({ root: kind, key: relative(root, path).replaceAll('\\', '/'), sha256: hash(path), sizeBytes: statSync(path).size }); else throw new Error('BACKUP_UNSUPPORTED_FILE'); } }; visit(root); return result; }
function copyVerified(sourceRoot: string, targetRoot: string, entry: BackupFile, overwrite = false): void { const source = join(sourceRoot, entry.key); if (!existsSync(source) || statSync(source).size !== entry.sizeBytes || hash(source) !== entry.sha256) throw new Error('BACKUP_ARTIFACT_INTEGRITY_ERROR'); const target = join(targetRoot, entry.key); mkdirSync(dirname(target), { recursive: true }); writeFileSync(target, readFileSync(source), overwrite ? undefined : { flag: 'wx' }); }
function writeManifest(path: string, manifest: BackupManifest): void { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, JSON.stringify(manifest, null, 2) + '\n', { flag: 'wx' }); }

/** Quiesces work before taking a consistent SQLite backup and hashed volume snapshot. */
export async function createBackup(input: { db: Database.Database; destination: string; artifactRoot: string; profileRoot: string; hooks: BackupHooks }): Promise<BackupManifest> { await input.hooks.stopWork(); await input.hooks.checkpoint(); await input.hooks.waitForSubmissions(); mkdirSync(input.destination, { recursive: true }); await input.db.backup(join(input.destination, 'application.sqlite')); const files = [...tree(input.artifactRoot, 'artifacts'), ...tree(input.profileRoot, 'profiles')]; for (const entry of files) copyVerified(entry.root === 'artifacts' ? input.artifactRoot : input.profileRoot, join(input.destination, entry.root), entry); const manifest: BackupManifest = { manifestVersion: 1, schemaVersion, createdAt: new Date().toISOString(), files }; writeManifest(join(input.destination, 'manifest.json'), manifest); return manifest; }
function readManifest(root: string): BackupManifest { const value = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8')) as BackupManifest; if (value.manifestVersion !== 1 || value.schemaVersion !== schemaVersion || !Array.isArray(value.files)) throw new Error('BACKUP_INCOMPATIBLE'); return value; }
/** Verifies the complete backup before replacing the database or volume files. */
export async function restoreBackup(input: { source: string; dbPath: string; artifactRoot: string; profileRoot: string; hooks: Pick<BackupHooks, 'stopWork'> }): Promise<BackupManifest> { const manifest = readManifest(input.source); const sourceDb = openDatabase(join(input.source, 'application.sqlite')); try { assertSchema(sourceDb); } finally { sourceDb.close(); } for (const entry of manifest.files) { const path = join(input.source, entry.root, entry.key); if (!existsSync(path) || statSync(path).size !== entry.sizeBytes || hash(path) !== entry.sha256) throw new Error('BACKUP_ARTIFACT_INTEGRITY_ERROR'); } await input.hooks.stopWork(); const temp = `${input.dbPath}.restore-${process.pid}`; writeFileSync(temp, readFileSync(join(input.source, 'application.sqlite')), { flag: 'wx' }); rmSync(input.dbPath, { force: true }); rmSync(`${input.dbPath}-wal`, { force: true }); rmSync(`${input.dbPath}-shm`, { force: true }); renameSync(temp, input.dbPath); const db = openDatabase(input.dbPath); try { assertSchema(db); const now = new Date().toISOString(); db.prepare('UPDATE dashboard_sessions SET revoked_at=? WHERE revoked_at IS NULL').run(now); db.prepare("INSERT INTO runtime_control VALUES (1,1,?) ON CONFLICT(id) DO UPDATE SET paused=1,updated_at=excluded.updated_at").run(now); } finally { db.close(); } for (const entry of manifest.files) copyVerified(join(input.source, entry.root), entry.root === 'artifacts' ? input.artifactRoot : input.profileRoot, entry, true); return manifest; }
